// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	site: 'https://r-punghoe.pages.dev',
	integrations: [
		starlight({
			title: 'R-punghoe',
			description: '알상무 공개 기록 아카이브 위키',
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/hjkwon-github/R-punghoe' }],
			sidebar: [
				{
					label: '시작하기',
					items: [
						{ label: '소개', slug: 'about' },
						{ label: '기록 원칙', slug: 'principles' },
						{ label: '기여하기', slug: 'contributing' },
						// Disclaimer page is owned by another workstream; it exists in the
						// repo, so it is safe to link here. If it is ever removed, this
						// slug must be removed too (Starlight errors on unresolved slugs).
						{ label: '면책·안내', slug: 'disclaimer' },
					],
				},
				{
					label: '기록실',
					items: [
						{ label: '연대기', slug: 'archive/timeline' },
						{ label: '용어사전', slug: 'archive/glossary' },
						{
							// Individual archive records. Autogenerated from the
							// `archive/records` directory: routed `.md` files appear here,
							// while files prefixed with `_` (e.g. _record-template.md)
							// are not routed and are skipped automatically.
							// Starlight v0.39+ requires the autogenerate config to live
							// inside an `items` array of a labelled group.
							label: '기록 목록',
							items: [{ autogenerate: { directory: 'archive/records' } }],
						},
					],
				},
			],
		}),
	],
});
